Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "learningchef/centos65"
  c.vm.box_url = "learningchef/centos65"
  c.vm.hostname = "default-centos65.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-node-default-centos65-d569a998-b97e-44e5-abfb-57140cf44252"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
